### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by Cypher1** [alexbaldwin/vimtips#1]
Love this extension but its very very white and bright at night (and really all the time).

Thanks

**Comment by schoettker** [comment]
Hey I just created a pull request for this, you can take a look here #2

**Comment by Cypher1** [comment]
Thanks, looks great!

@alexbaldwin can you review the code? Thanks

**Comment by alexbaldwin** [comment]
@Cypher1 thanks for your help, merged in now.

**Comment by Cypher1** [comment]
It was all @schoettkr 
Thanks @schoettkr :D
